### ISSUE TITLE
Improving Uploads of Big Files via Web Browsers

### ISSUE THREAD

**Issue by lidel** [ipfs/in-web-browsers#115]
This a a meta-issue tracking known issues and ongoing improvements related to uploads of big (1GB+) files in web browser contexts.

### Known Problems with  HTTP API 

Invalid progress reporting:
- [ ] Streaming versions of ipfs.files.add buffer entire data in memory before doing HTTP POST (https://github.com/ipfs/js-ipfs-api/issues/842)

Browser crash <200MB:
- [ ] crash when dropping a big file (https://github.com/ipfs-shipyard/ipfs-companion/issues/464)
- [ ] Uploading big files crush page in Chrome (https://github.com/ipfs/js-ipfs-api/issues/654)
- [ ] upload-file-via-browser can only upload file size less than 165MB (https://github.com/ipfs/js-ipfs-api/issues/788)

Silent crash in Firefox when Buffer max size is breached:
- [ ]  crash when dropping a big file (https://github.com/ipfs-shipyard/ipfs-companion/issues/464)

**Comment by olizilla** [comment]
This looks worth tracking, as it's being in an [origin trial in chromium](https://developer.chrome.com/origintrials/#/view_trial/3524066708417413121) and has support from firefox, edge, and safari

> Fetch upload streaming lets web developers make a fetch with a ReadableStream body. 
> 
> – https://www.chromestatus.com/feature/5274139738767360

The linked design doc is great https://docs.google.com/document/d/e/2PACX-1vQ26giyHPPhxrgVorNtkVSsJPOWecc6c6wHFLFbbl27r0BIBEgRwahh2b37Uk7HfXvZoW1Cu_ed-bRm/pub
