### ISSUE TITLE
HTTP Headers Cleanup: API and Gateway

### ISSUE THREAD

**Issue by lidel** [ipfs/in-web-browsers#132]
### Summary

We should have:

- [Interop](https://github.com/ipfs/interop) tests that ensure HTTP responses have the same headers and values, no matter which implementation is the backend 

- Diagnostic tool/script that can be run against any HTTP API or Gateway  port and provide quick health status

### Status

- 2018-Q4: Interop is a mixed bag. Some headers are tested, some are not or different values across implementations. A simple test script exists but is incomplete.

### TODO

Go over below _headers of interest_ and ensure proper safeguards are in place. 

#### Gateway
- [ ] `X-Ipfs-Path`: IPFS Path of returned resource
- [ ] `Etag`: resolved CID/multihash of returned payload
- [ ] `Cache-Control`: disable cache for directory listings and errors,
  enable heavy caching for immutable assets from `/ipfs/` namespace
- [ ] `Suborigin`: use root CID in base32 and literal prefix to conform
  to the current suborigin spec (https://github.com/ipfs/in-web-browsers/issues/66)

#### API
- [ ] `Etag` & `Cache-Control`:  without this, all content addressed "gets" skip browser cache which results in degraded performance and wasted bandwidth (details: https://github.com/ipfs/go-ipfs/issues/3543)
- [ ] `X-Chunked-Output`: various API endpoints break without  it (eg.  https://github.com/ipfs/go-ipfs/issues/5711)
- [ ] `Access-Control-Expose-Header`: without this, JS is unable to see  `X-Chunked-Output` in Chrome  (https://github.com/ipfs/go-ipfs/issues/5745)

### Related

- Examples of issues that occur if we don't have regression tests for gateway 
  - https://github.com/ipfs-shipyard/ipfs-share-files/issues/17#issuecomment-416766663: _Gateway requests responds with 403 - Forbidden_ 
  - https://github.com/ipfs/go-ipfs/issues/5711: _Unexpected X-Chunked-Output in /api/v0/version response_ 
- https://github.com/ipfs/js-ipfs/pull/1537: _adding X-Ipfs-Path, Etag, Cache-Control, Suborigin to js-ipfs_
- https://github.com/ipfs/go-ipfs/issues/3543: _Add etag and other caching headers to all content addressed gets in api_
- [public-gateway-smoke-test.sh ](https://github.com/ipfs/infrastructure/pull/430) – Small test suite ensuring Public HTTP Gateway behaves correctly, all CORS headers and permissions are in place etc.

**Comment by lidel** [comment]
### `-Allow-Headers` vs `-Expose-Headers`

There is an important nuance: `Access-Control-Allow-Headers` tells browsers which headers can be used in XHR CORS **request** and `Access-Control-Expose-Headers` whitelists which **response** headers will be available to be read by JS:

> The [`Access-Control-Allow-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers) response header is used in response to a preflight [HTTP `OPTIONS`] request  which includes the Access-Control-Request-Headers to indicate which HTTP headers can be used during the actual **request**.

> The [`Access-Control-Expose-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) response header indicates which headers can be exposed as part of the **response** by listing their names.
