### ISSUE TITLE
Move IPFS addressing spec to ipfs/specs

### ISSUE THREAD

**Issue by lidel** [ipfs/in-web-browsers#147]
The best and **up-to-date source of truth about IPFS addressing right now is in** [ADDRESSING.md](https://github.com/ipfs/in-web-browsers/blob/master/ADDRESSING.md) memo.

As more and more people add IPFS support to their software, especially on the web,
we should decrease noise and increase signal around addressing by adding proper technical spec doc to the [ipfs/specs](https://github.com/ipfs/specs) repo, as suggested in https://github.com/ipfs/specs/issues/138.

#### Prior Art

- 2019:  WIP on IPFS addressing (https://github.com/ipfs/go-ipfs/issues/5287, https://github.com/ipfs/in-web-browsers/issues/118)
- 2018: [ADDRESSING.md](https://github.com/ipfs/in-web-browsers/blob/master/ADDRESSING.md) memo is created as a techncial summary from branch below
- 2017-2018: [ipfs/specs/dweb-addressing](https://github.com/ipfs/specs/tree/addressing/dweb-addressing) branch with lots and lots of notes
- 2015-2017: Memo with Background on Address Scheme discussions: https://github.com/ipfs/specs/pull/152 
- 2017: Tackle identifying origins https://github.com/ipfs/in-web-browsers/issues/6
- 2015: First discussion about addressing schemes https://github.com/ipfs/go-ipfs/issues/1678

#### TODO

- [ ] create a new PR to `ipfs/specs` (consolidate technical content from Prior Art)
    - [ ] PR should aim to close https://github.com/ipfs/specs/issues/138
    - [ ] close https://github.com/ipfs/specs/pull/139 and point at new PR
- [ ] ensure it covers `/ipns/` as well (https://github.com/ipfs/go-ipfs/issues/5287, https://github.com/ipfs/in-web-browsers/issues/118)
- [ ] get it merged to [ipfs/specs](https://github.com/ipfs/specs) repo 
- [ ] update `ADDRESSING.md` to point at the doc in [ipfs/specs](https://github.com/ipfs/specs)
- [ ] close remaining issues/PRs about addressing with comment pointing at document in specs repo (add links below so we don't forget)
  - [ ] https://github.com/ipfs/interface-js-ipfs-core/issues/287
  - [ ] https://github.com/ipfs/docs/issues/91
  - [ ] https://github.com/ipfs/go-ipfs/issues/1678
  - [ ] https://github.com/ipfs/in-web-browsers/issues/118
  - [ ] https://github.com/ipfs/specs/issues/138
  - [ ] https://github.com/ipfs/in-web-browsers/issues/6
- [ ] identify remaining content from Prior Art that could be extracted into [ipfs/blog](https://github.com/ipfs/blog/) post or less technical [ipfs/docs](https://github.com/ipfs/docs/issues/91)

cc https://github.com/ipfs/in-web-browsers/issues/118 https://github.com/ipfs/in-web-browsers/issues/3 ipfs/ipfs#227 ipfs/in-web-browsers#4 ipfs/in-web-browsers#28 https://github.com/ipfs/specs/pull/139 @autonome

**Comment by vanrein** [comment]
> ```
> ip[nf]s://<domain.name>/object
> ```
> 
> Retrieval would be processed as "DNS look up `domain.name IN TXT`, resolve resulting IPFS/IPNS identifier, retrieve `object`".

I was reading this, hoping to find just that.  IPFS wants to get away from hosting locations for reasons of persistency, but IPNS is different.  I love the idea of using DNS (and DNSSEC) and getting very powerful bookmarks:

 1. Stored domain name, for human reference where it once originated from
 2. Stored IPNS key, so we can lookup the names from anyone who pins them, along with new versions from the same origin
 3. Stored IPFS hash, so we can retrieve the version that we bookmarked for as long as it is pinned

I will add the spec to my reading list, it's useful stuff!

**Comment by hsanjuan** [comment]
@lidel: double-check that you want me to move this issue to /ipfs/specs/, correct?

**Comment by lidel** [comment]
@hsanjuan correct
