### ISSUE TITLE
Enabling WebRTC Transport in Browser

### ISSUE THREAD

**Issue by lidel** [ipfs/in-web-browsers#153]
> This issue tracks what needs to happen before we enable WebRTC transport in JS-IPFS by default. It also acts as an entry point to existing resources in other repos.

### Current Status

- [js-libp2p-webrtc-star](https://github.com/libp2p/js-libp2p-webrtc-star) - libp2p WebRTC transport that includes a discovery mechanism provided by the signalling-star
  - caveat: opt-in, JS-only, centralized signaling service is a single point of failure

- [go-libp2p-webrtc-direct](https://github.com/libp2p/go-libp2p-webrtc-direct) / [js-libp2p-webrtc-direct](https://github.com/libp2p/js-libp2p-webrtc-direct) - A libp2p transport that enables browser-to-server, and server-to-server, direct communication over WebRTC without requiring signalling servers ([examples](https://github.com/libp2p/go-libp2p-webrtc-direct/tree/master/examples))
  - caveat: opt-in, point-to-point, no browser-browser

### Goals

- Transport that does not require hardcoding centralized signaling server to work and is stable enough to be enabled by default in JS IPFS.

- [RTCDtlsTransport API: getRemoteCertificates](https://www.w3.org/TR/webrtc/#dom-rtcdtlstransport-getremotecertificates) could in theory let webrtc handle encryption & stream muxing  in the browser. Unfortunately it is [not supported by Firefox](https://caniuse.com/#search=getRemoteCertificates).. [yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1307996).

### Ongoing IPFS Work

- [ ] Sunsetting the *-star protocols: https://github.com/libp2p/js-libp2p/issues/385
- [ ] Distributed signaling protocol (removes need for ws-star)
  - initial proposal: https://github.com/libp2p/specs/pull/159
  - early design: https://github.com/libp2p/js-libp2p/issues/385#issuecomment-514300699

### External Work

- WebRTC WG at W3C looking for DHT/P2P use cases for webrtc-nv: https://github.com/libp2p/js-libp2p-webrtc-star/issues/177 
- Mozilla:
	- [ ]  [Bug: Implement the RTCDtlsTransport interface](https://bugzilla.mozilla.org/show_bug.cgi?id=1307996)
- Chromium:
  - [QUIC DataChannels](https://github.com/arewedistributedyet/arewedistributedyet/issues/30)

### References

- WebRTC and DWeb analysis https://github.com/arewedistributedyet/arewedistributedyet/issues/7
- https://w3c.github.io/webrtc-pc/#peer-to-peer-connections
- https://caniuse.com/#search=getRemoteCertificates

**Comment by mitra42** [comment]
Maybe I missed it, but did you fix the problems that made webRTC not work before - if I remember correctly (and its possible I don't) it was a problem with JS-IPFS needing lots of connections and webRTC having very high per-connection overhead.

**Comment by lidel** [comment]
I believe its partially adressed: js-ipfs added [support](https://github.com/ipfs/js-ipfs#optionsconnectionmanager) for [libp2p's ConnectionManager](https://github.com/libp2p/js-libp2p-connection-manager#create-a-connectionmanager), which enables us to set limits on the number of connections maintained by js-ipfs.

**Comment by backkem** [comment]
Why do you need getRemoteCertificates? Can't PeerConnection handle both stream muxing and encryption:
- stream muxing: Just open multiple Data Channels.
- encryption: Everything is sent over DTLS. The certificates are inherently verified by the signaling.
  - Is there a need to manually verify? You could do this against the fingerprint in the SessionDescription.
  - Or is there actually a need to extract the remote certificate? Knowing the the security is dealt with end-to-end by WebRTC already.

**Comment by lidel** [comment]
Work towards enabling WebRTC transport in Kubo is planned/tracked in https://github.com/ipfs/kubo/issues/9724
