### ISSUE TITLE
Clear-Site-Data when loaded via path gateway

### ISSUE THREAD

**Issue by lidel** [ipfs/in-web-browsers#157]
## Motivation

Websites loaded via path gateway are able to access cookies and storage of the entire domain. While we are moving to [subdomain gateways](https://docs-beta.ipfs.io/how-to/address-ipfs-on-web/#subdomain-gateway) (#89), requests made to path gateways will continue to lack origin isolation between content roots. 

## TL;DR

1.  [subdomain gateways](https://docs-beta.ipfs.io/how-to/address-ipfs-on-web/#subdomain-gateway) will provide Origin isolation
2.  [path gateways](https://docs-beta.ipfs.io/how-to/address-ipfs-on-web/#path-gateway) do not
3. > The `Clear-Site-Data header` clears browsing data (cookies, storage, cache) associated with the requesting website. It allows web developers to have more control over the data stored locally by a browser for their origins.
   > – https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data

## Potential use

We could leverage `Clear-Site-Data` header and send a hint to user agent to clear any preexisting cookies and storage. This is a "nuclear option", but could incentivize users to switch to subdomain gateways when access Web APIs relying on Origin is required. 

Note: this requires native subdomain support (https://github.com/ipfs/go-ipfs/issues/6498) to land first.

### Implementation

To purge cookies and storage without reloading any contexts, below header would be returned with every response from `/ipfs/{cid}` and `/ipns/{foo}` paths:

```
Clear-Site-Data: "cookies", "storage"
```

### TODO

- [ ] create PoC proxy to validate the idea
- [ ]  document behavior in Firefox
- [ ]  document behavior in Chromium
- [ ]  document behavior in Safari

**Comment by lidel** [comment]
Blocking cookies is a nuclear option that may break some deployments behind reverse proxies that pass all headers. We would need `NoWebSecurity` flag (`false` by default) in case someone really wants to disable things like `Clear-Site-Data` in contexts that provide no origin isolation.

**Comment by lidel** [comment]
Something to be aware of: `executionContexts` and wildcard directives are not recognized by Chromium ([bug-898503](https://crbug.com/898503))

**Comment by lidel** [comment]
Specs suggest discrepancy between how cookies and storage are handled:
https://www.w3.org/TR/2017/WD-clear-site-data-20171130/#grammardef-storage
https://www.w3.org/TR/2017/WD-clear-site-data-20171130/#grammardef-cookies

Storage is purged for origin, but cookies are purged for origin + all origins based on subdomains. TODO: check if vendors implement the spec 1:1, or so something else.

**Comment by lidel** [comment]
Sidenote: we could reuse this on locked-down subdomain namespace  https://github.com/ipfs/go-ipfs/issues/7318 (think `cors.dweb.link/ipfs/`) that is optimized for loading data/subresources and not website roots:
- path gateway
- has liberal CORS (`*`)
- has locked-down web APIs like storage

**Comment by darobin** [comment]
I would like to suggest taking the restrictions on `Permissions-Policy` (which was called `Features-Policy` when this issue was opened — @lidel mentions it at the top) further ([spec](https://w3c.github.io/webappsec-permissions-policy/), [mdn](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy)). When you load a random web page, a number of features are available generally gated by some kind of permission or interaction. That is often okay (or at least it's understood to be a managed risk) but it is open to phishing or other forms of social engineering.

I think that in a pathed context, we can restrict this further and make those powerful capabilities unavailable. The header would look like this:

```
Permissions-Policy: accelerometer=(),ambient-light-sensor=(),attribution-reporting=(),autoplay=(),battery=(),
                    bluetooth=(),browsing-topics=(),camera=(),ch-device-memory=(),ch-downlink=(),
                    ch-dpr=(),ch-ect=(),ch-lang=(),ch-prefers-color-scheme=(),ch-rtt=(),ch-save-data=(),
                    ch-ua=(),ch-ua-arch=(),ch-ua-bitness=(),ch-ua-full=(),ch-ua-full-version=(),
                    ch-ua-full-version-list=(),ch-ua-mobile=(),ch-ua-model=(),ch-ua-platform=(),
                    ch-ua-platform-version=(),ch-ua-reduced=(),ch-ua-wow64=(),ch-viewport-height=(),
                    ch-viewport-width=(),ch-width=(),clipboard-read=(),clipboard-write=(),conversion-measurement=(),
                    cross-origin-isolated=(),direct-sockets=(),display-capture=(),document-domain=(),
                    encrypted-media=(),execution-while-not-rendered=(),execution-while-out-of-viewport=(),
                    federated-credentials=(),focus-without-user-activation=(),fullscreen=(),gamepad=(),
                    geolocation=(),gyroscope=(),hid=(),idle-detection=(),interest-cohort=(),
                    join-ad-interest-group=(),keyboard-map=(),local-fonts=(),magnetometer=(),microphone=(),
                    midi=(),navigation-override=(),otp-credentials=(),payment=(),picture-in-picture=(),
                    publickey-credentials-get=(),run-ad-auction=(),screen-wake-lock=(),serial=(),shared-autofill=(),
                    shared-storage=(),speaker-selection=(),storage-access-api=(),sync-script=(),sync-xhr=(),
                    trust-token-redemption=(),unload=(),usb=(),vertical-scroll=(),wake-lock=(),web-share=(),
                    window-placement=(),xr-spatial-tracking=()
```

So, errr, yeah, your eyes might be bleeding right now and I'm sorry about that. Also, that list grows all the time. It's not great. There are issues about making a blanket "remove anything that might be dangerous" mode but so far they haven't been accepted.

We could decide to keep some things allowed (like camera or sync XHR) if we're worried about breaking legit use cases. But at least this list (which is the most comprehensive I could find — I'm looking into whether there's a reliable way to get an up-to-date list) makes things pretty tight and safe, on top of CSP and clearing the data.

**Comment by lidel** [comment]
Pretty  hardcore, but for sure will do the trick of forcing people to move to subdomain gateways.

I propose we do a test run: set  `Permissions-Policy`, `Clear-Site-Data` and a strict `Content-Security-Policy`  on `ipfs.io` first, in Nginx, and see if there are any screams from the distance. 

If the sky does not fall, me and @hacdias  can apply this to all path requests in [go-libipfs/gateway](https://github.com/ipfs/go-libipfs/tree/main/gateway) library.

**Comment by darobin** [comment]
In addition to `Permissions-Policy`, I think the following would be good:

```
Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data: ; form-action 'self'; connect-src 'self' data: ; manifest-src 'none' ; object-src 'none' ; sandbox allow-forms allow-modals allow-scripts allow-top-navigation-by-user-activation
Clear-Site-Data: "cookies", "storage"
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
```

Some quick notes:
* I reviewed the options for `Clear-Site-Data` and agree with your original proposal.
* For the CSP, I don't include `blob:` which means no file uploads (even locally). One thing that we could add (dynamically) would be the URL up to the CID inclusive (eg. `https://ipfs.io/ipfs/someCID/`) instead of `'self'` for default/connect/form.
* I didn't block `navigate-to`, I think linking to other sites should be ok (but I can change my mind). 
* I didn't block `worker-src` because I don't think that there's much left that a worker could do, but it's easy to add.
* I don't think that we want CSP reporting, but it's easy enough to add.
* I didn't include `allow-same-origin` in `sandbox`, that's pretty strict and might break things. What this does is that it puts the document in a weird origin of its own, all alone, and _every_ request from that becomes cross-origin, which means that doing things that would require CORS when talking to another server now require CORS when talking to the same server, which is pretty neat. One issue is that it blocks font loading (because fonts require CORS) — maybe that's a problem? Alternatively, we could keep this strong and add `Access-Control-Allow-Origin: this.site` on requests that match fonts. I haven't found a way to have this sandboxing but not for fonts.
* I believe that you already have `nosniff`, threw it in for completeness.
* `X-Frame-Options` in case anyone is trying to inject this in an iframe elsewhere.

I did some very superficial testing on static content, and it works. If you want to play with it locally, run this with a path to a dir to serve from:

```js
#!/usr/bin/env node

import process from 'process';
import express from 'express';
const app = express();

app.use((req, res, next) => {
  res.set({
    'Permissions-Policy': 'accelerometer=(),ambient-light-sensor=(),attribution-reporting=(),autoplay=(),battery=(),bluetooth=(),browsing-topics=(),camera=(),ch-device-memory=(),ch-downlink=(),ch-dpr=(),ch-ect=(),ch-lang=(),ch-prefers-color-scheme=(),ch-rtt=(),ch-save-data=(),ch-ua=(),ch-ua-arch=(),ch-ua-bitness=(),ch-ua-full=(),ch-ua-full-version=(),ch-ua-full-version-list=(),ch-ua-mobile=(),ch-ua-model=(),ch-ua-platform=(),ch-ua-platform-version=(),ch-ua-reduced=(),ch-ua-wow64=(),ch-viewport-height=(),ch-viewport-width=(),ch-width=(),clipboard-read=(),clipboard-write=(),conversion-measurement=(),cross-origin-isolated=(),direct-sockets=(),display-capture=(),document-domain=(),encrypted-media=(),execution-while-not-rendered=(),execution-while-out-of-viewport=(),federated-credentials=(),focus-without-user-activation=(),fullscreen=(),gamepad=(),geolocation=(),gyroscope=(),hid=(),idle-detection=(),interest-cohort=(),join-ad-interest-group=(),keyboard-map=(),local-fonts=(),magnetometer=(),microphone=(),midi=(),navigation-override=(),otp-credentials=(),payment=(),picture-in-picture=(),publickey-credentials-get=(),run-ad-auction=(),screen-wake-lock=(),serial=(),shared-autofill=(),shared-storage=(),speaker-selection=(),storage-access-api=(),sync-script=(),sync-xhr=(),trust-token-redemption=(),unload=(),usb=(),vertical-scroll=(),wake-lock=(),web-share=(),window-placement=(),xr-spatial-tracking=()',
    'Content-Security-Policy': `default-src 'self' 'unsafe-inline' 'unsafe-eval' data: ; form-action 'self'; connect-src 'self' data: ; manifest-src 'none' ; object-src 'none' ; sandbox allow-forms allow-modals allow-scripts allow-top-navigation-by-user-activation`,
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'sameorigin',
  });
  next();
});
app.use(express.static(process.argv[2]));
app.listen(8888, () => console.warn(`Listening on http://localhost:8888`));
```
