### ISSUE TITLE
Create a Roadmap with Steps to Being Native in Web Browsers

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#23]
Complete the [ROADMAP.md](https://github.com/ipfs/in-web-browsers/blob/master/ROADMAP.md)

- [ ] Fill out all the steps
- [ ] Situate within the broader effort to upgrade the web - see "Browser Upgrade Path" in [these slides](https://ipfs.io/ipfs/QmW3ZuVxXmwgpdXUD71Wi6XuMPWTPuGk7cNhdmbotwjKQu/ipfs-036.upgrade-path.pdf)
- [ ] Validate the plan with people who know how browser teams work

**Comment by flyingzumwalt** [comment]
@nicola here are the notes from our conversation. https://github.com/ipfs/in-web-browsers/blob/feat/roadmap/roadmap-stages-of-integration.md  It's a mess right now -- our notes barely captured half of what we discussed 😞

**Comment by flyingzumwalt** [comment]
I'm struggling around security models. Writing a protocol handler that runs ipfs and exposes the ipfs core interface (see #39 and its sub-issues) is not the hard part. The real challenge is to expose that functionality in a way that is safe. See #43 (huge topic).

Without a framework for thinking about these security models, it's hard to sort out what the roadmap should look like. What are the stages of adoption/integration? It's clear that there are certain stopping points where you can provide XYZ functionality without creating vulerability A, but can't safely allow some other functionality until you address that vulnerability...

**Comment by SgtPooki** [comment]
@lidel @BigLep Is this something we need to keep updated? Who owns this?
