### ISSUE TITLE
Sort out an Address Scheme that fits with Browser Security Model

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#3]
## Acceptance Scenario

- [ ] Propose an address scheme that fits with Browser Security Model
- [ ] Provide working code that shows the address scheme working, and how it can be supported in the browser
- [ ] (optional) #4 Document the motivations for the more general fs: namespace and address scheme
- [ ] #6 Tackle identifying origins with (or without?) fs:// paths
- [ ] #7 Reconcile IPFS absolute addresses with standard URL resolution

## Background

The proposed use of `ipfs/` at the root of addresses in the `fs:` namespace like`fs://ipfs/{content hash}` conflicts with the single-domain content origin policy that is central to the browser security model.  This brings into question the whole idea of a generic `fs:` namespace rather than `ipfs:`

**Comment by lgierth** [comment]
The discussion for this is largely happening in #6.
