### ISSUE TITLE
Unify the WebExtensions effort, make them modular pieces and more useful.

### ISSUE THREAD

**Issue by diasdavid** [ipfs/in-web-browsers#54]
It gets me super pumped to see so many endeavors started to get IPFS running on a browser extension so that it becomes easier to make it available without hassle to its users. At the same time, I also feel that we lost some of the enthusiasm from other members in the community by having so many WebExtensions efforts started, each with its own qualities and learnings, but scattered across different user accounts and orgs. It is the time for us to laser focus and take all of those endeavors together into a more solid that it is easier to understand and for the community to contribute.

I come here to propose a new nomenclature for the WebExtensions projects and to converge some. I've heard several people wishing for this to happen in our Monday calls.

### Currently, we have:

- https://github.com/lidel/ipfs-firefox-addon
- https://github.com/whyrusleeping/ipfs-webext
- https://github.com/VictorBjelkholm/js-ipfs-in-the-browser
- https://github.com/fbaiodias/ipfs-chrome-station (uses parts of station UI)
- https://github.com/ipfs/station - UI to interact with a Node
- https://github.com/ipfs/webui - Another UI to interact with a node
- _Let me know if I missed any_

### What I want to have:

- `webext-js-ipfs` - The most simple WebExtension with js-ipfs, offering a base layer for all the other WebExtensions.
- `webext-go-ipfs` - Same as above, but with go-ipfs as its engine, might require a harder set up (due to binaries) but it will offer the same API thanks to [`interface-ipfs-core`](https://github.com/ipfs/interface-ipfs-core), which means that any other WebExtension will be able to swap internals without a problem.
- `webext-station` - https://github.com/lidel/ipfs-firefox-addon meets https://github.com/fbaiodias/ipfs-chrome-station. A byproduct of this would be that station becomes just an UI that then `electron-station` can also use.

### Action plan

This is my proposal action plan, assuming that @whyrusleeping @VictorBjelkholm and @lidel would be ok with bringing their repos to the IPFS org and renaming their repos for clarity. _Don't take it for granted until it has been agreed upon by everyone involved_.

- [ ] [Upgrade `https://github.com/VictorBjelkholm/js-ipfs-in-the-browser` to `webext-js-ipfs`](https://github.com/VictorBjelkholm/js-ipfs-in-the-browser/pull/2)
  - [ ] Move it to the IPFS org
  - [ ] Update docs to match the quality of the Go counterpart 
  - [ ] Update docs to reference the Go counterpart
- [ ] Rename https://github.com/whyrusleeping/ipfs-webext to `webext-go-ipfs`
  - [ ] Move it to the IPFS org
  - [ ] Update docs to reference the JS counterpart
- [ ] Bring https://github.com/lidel/ipfs-firefox-addon to the IPFS org
  - [ ] Rename it webext-station
  - [ ] Make it work on top of either `webext-go-ipfs` and `webext-js-ipfs`
  - [ ] Bring the UI from @fbaiodias chrome-extension
  - [ ] Implement remaining features requested throughout this repo
- Future
  - [ ] Factor the UI on its own module
  - [ ] Integrate the new polished UI with electron-station.

I'm happy to lead this if everyone is happy with joining efforts. We can have a weekly or biweekly sync up. I really want to see this happen :)

**Comment by lidel** [comment]
Quick summary on what is provided by mentioned repos:  
 - `whyrusleeping/ipfs-webext`  is a simple redirect to HTTP Gateway: this code is already in WebExtension rewrite of  `ipfs-firefox-addon` 
- `VictorBjelkholm/js-ipfs-in-the-browser` does not provide IPFS Gateway functionality. It spawns `js-ipfs` and exposes  it as `window.IpfsAPI` object on every page, but does not provide HTTP gateway that could be used for redirects.
- `lidel/ipfs-firefox-addon` rewrite to WebExtension version is in `master` branch ([try latest ALPHA here](https://github.com/lidel/ipfs-firefox-addon/releases)), legacy version is in `legacy-sdk` branch.

----

My thoughts regarding future of  `lidel/ipfs-firefox-addon`:

-  👍 for bringing maintenance of `ipfs-firefox-addon` under IPFS org

   - Is there some kind of how-to I could follow? Will old URLs work?

    - Old extension will continue working [until Firefox 57](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/).  Right now it has [~500 daily users](https://i.imgur.com/iIcidnS.png).  I released some [alpha versions of WebExtension](https://github.com/lidel/ipfs-firefox-addon/releases) and migration went ok for users who opted-in for development channel.

   - The [Bus Factor](https://en.wikipedia.org/wiki/Bus_factor) of the project is my main concern right now. I want to ensure smooth ownership transition similar to experience with WebExtension migration: 
       - Protocol Labs should create own account at [AMO](http://addons.mozilla.org/), so that it looks official and is not tied to a single individual  
       - Plan A: I should be able to add someone else as an owner of my add-on, that way no user interaction would be needed. New update would just be pushed to current users.  
       - Plan B: If that does not work I can simply push update that asks users to migrate manually to "Protocol Labs" version. 

- I may be missing something, but it looks that both `webext-go-ipfs`  and `webext-js-ipfs` would be only used by `webext-station`. Not sure what value is added by proposed modularization, due to the way WX is constructed it may introduce unnecessary maintenance burden.  
The only reusable part I see is UI. 
Perhaps for now all three modules should be replaced with one repo: `webext-station`?

**Comment by VictorBjelkholm** [comment]
from @diasdavid 
> What I want to have:
> webext-js-ipfs
> webext-go-ipfs
> webext-station

For me, it's not clear what benefit we would get from separating all these extensions. As I understand webext-station would have a UI to interact with your pinned content, but the webext-x-ipfs would not? Instead, I would propose a all-in-one solution, where we have `ipfs-extension` working for any browser implementing the Web Extension standard, doing both. The name would simply be `ipfs-extension` and would expose either a js-ipfs or js-ipfs-api node connected to x-ipfs. In the beginning, we would just have js-ipfs, but allow people to install go-ipfs manually and point their extension there. This extension would also come with the work @lidel have done and do redirects properly (or even just load content into about:blank if it's from ipfs.io/ipfs/X)

I guess the main question, why three different extensions instead of one?

> Is there some kind of how-to I could follow? Will old URLs work? If not, perhaps making a fork would be a better approach?

There is a "Transfer ownership" button under /settings in your repository, and Github will create redirects from the old repository.

from @lidel 
>  Perhaps for now all three modules should be replaced with one repo: webext-station?

Yes, agree! With one modification, a simpler name: `ipfs-extension`

As a note: I'll be happy to participate and help out where needed, especially when it comes to the js-ipfs extension.

**Comment by diasdavid** [comment]
Thanks for the quick reply here!

To answer the question that both had "Why we need 3 instead of one", let me clarify: I didn't intend to propose to host, maintain and publish 3 WebExtensions, I agree with you, there is value to have to have just one that users can install and use. My proposal for `webext-js-ipfs` and `webext-go-ipfs` is to have base WebExtensions to enable other developers to implement on top, it is common to see the question of "how can we bundle IPFS in a WebExtension" and those two repos would be the answer. This way we would simplify `webext-{js,go}-ipfs` to the minimum of spawning and run the node, without duplicating functionality that is present on `webext-station`.

As for `webext-station`, it would be the one to pack all of the features like redirecting, pinning, etc. This WebExtension is the one we want to recommend to users.

> Is there some kind of how-to I could follow? Will old URLs work? If not, perhaps making a fork would be a better approach?

Github has redirects in place when there is a rename or migration

> Old extension will continue working until Firefox 57. Right now it has ~500 daily users. I released some alpha versions of WebExtension and migration went ok for users who opted-in for development channel.

Awesome!

>The Bus Factor of the project is my main concern right now. I want to ensure smooth ownership transition similar to the experience with WebExtension migration:

We can have a org account + add the individuals participating in the project. Let's try by adding mine first, my user is: https://addons.mozilla.org/en-US/firefox/user/david_dias/

> On the name

I'm happy to new name suggestions, I suggested `station` since we are reusing/iterating on the UI which can then later be ported back to the electron app too. Station was a good accepted name last time we asked the community for something that installs an IPFS node in a user machine. Names like `ipfs-extension` are misleading since they don't invoke directly what they are doing, appending the word extension could mean it is an extension to the IPFS protocol, to the daemon and so on.

**Comment by whyrusleeping** [comment]
@lidel it's worth noting that the main thing my extension provides is the
ability to start up a go-ipfs node on it's own. Beyond that, there's
nothing to it. I'd love to merge that functionality with yours

**Comment by diasdavid** [comment]
@lidel just invited you to https://github.com/orgs/ipfs/teams/javascript-team, so you can transfer the repo and have permissions right away.

> I'd love to merge that functionality with yours

❤️ @whyrusleeping 

> Perhaps a better place for "WebExtension examples" would be already existing /examples subdirectory?

Yeah, good point, we just need a repo and a folder called examples, although I prefer and recommend for these examples to be inside the `webext-station` itself, it will be the first place people look for WebExtension material. 

> you should be able to access management panel and be listed as developer here. Looks good!

Got it! Thank you :)

**Comment by lidel** [comment]
Voila! https://github.com/ipfs/ipfs-firefox-addon ✨ 

I did not know which teams should have writable access, so I did not select any and locked myself out  🥇 
Perhaps we could have "WebExtensions" team with involved people?

**Comment by lidel** [comment]
Ok, seems that redirects work fine. Ownership is transferred, what is left is name change (tracked in https://github.com/lidel/ipfs-firefox-addon/issues/225), but that will be done by someone with admin rights in IPFS org. 

FYI  I've had `master` protection enabled, and it transferred along with `ipfs-firefox-addon` repo.
It means that PRs are the only way of changing `master` by non-admins and every PR requires to be accepted by at least 1 reviewer. 
I am personally okay with it, but feel free to change this behavior if you find it too intrusive.

**Comment by kyledrake** [comment]
My thoughts:

* +1 one addon to rule them all (ipfs-addon or named something similar). @lidel's webext port seems like the perfect base for this. Should work with Firefox & Chrome.
* Once the webext version is launched and polished a bit, the addon should just be linked from the front ipfs.io site with a big shiny install button. My hunch is this will be the main UX flow for most people interested in IPFS.
* Some integrated docs and resources should be provided for people that just installed the plugin and want to try it out.

**Comment by diasdavid** [comment]
@lidel ❤️🎇🎉 \o/!

Also, got ya. You should have access now.
![image](https://cloud.githubusercontent.com/assets/1211152/25867120/e68f625c-34f8-11e7-8932-2c7577e5dc26.png)

> master protection enabled

Yes, love that feature :) Although we actually have a good having always reviewing each other's PR and letting CI run so that we don't hit any issue.

> @lidel's webext port seems like the perfect base for this. Should work with Firefox & Chrome.

Yeah, 100% agreed

> webext version is launched and polished a bit...

Yeah, let's do that, bunch of tasks on the repo issues, wanna help @kyledrake ? I know you are also busy with electron-ipfs and many many other things so no worries :)

**Comment by diasdavid** [comment]
@lidel is doing crushing it developing https://github.com/ipfs/ipfs-companion, now full Web Extension with Chrome and Firefox support. If you were following this issue and haven't checked the extension, make sure you do! :)

**Comment by diasdavid** [comment]
Let's focus our energies and redirect convos around WebExtensions to https://github.com/ipfs/ipfs-companion. @lidel has been doing an amazing job at championing the development of it! 👏🏽👏🏽👏🏽
