### ISSUE TITLE
Public IRC Channel for Web Browsers Working Group

### ISSUE THREAD

**Issue by lidel** [ipfs/in-web-browsers#67]
## Background

Right now we have `#ipfs` and `#ipfs-dev`.  

There is a pending Action Item  from [Q1 Planning/Brainstorming](https://github.com/ipfs/in-web-browsers/blob/master/meeting-notes/2017-12-29--q1-planning-brainstorming.md#action-items):
create a IRC channel dedicated to this endeavour. 

## Tasks
- [x] @diasdavid please comment if this Action item is still valid:
     - If yes, can I do it? or do you want to set it up yourself?
     -  If not, please close this :)
- [x] Pick a name (`#ipfs-in-web-browsers` ? suggestions welcome)
- [x] Set up channel
- [ ] Set up log archive (like https://botbot.me/freenode/ipfs/)
- [ ] Add it to `README` of this repo so that folks interested in the topic can join

**Comment by diasdavid** [comment]
@lidel go for it :)

**Comment by lidel** [comment]
Done!
We now have `#ipfs-in-web-browsers`  ✨
